/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Metaheuristicas_Practica_3;

import java.awt.Image;
import java.util.LinkedList;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author David
 */
public final class Consola extends javax.swing.JFrame {

    private int eleccion;
    
    
    /**
     * Creates new form Consola
     */
    public Consola() {
        List<Image> lista = new LinkedList<>();
        lista.add(new ImageIcon(
                "src/main/resources/icons/ant_16.png").getImage());
        lista.add(new ImageIcon(
                "src/main/resources/icons/ant_20.png").getImage());
        lista.add(new ImageIcon(
                "src/main/resources/icons/ant_40.png").getImage());
        lista.add(new ImageIcon(
                "src/main/resources/icons/ant_64.png").getImage());
        
        initComponents();
        this.setIconImages(lista);
        this.eleccion = 0;
        this.jProgressBarEstado.setVisible(true);
        
    }

    
    public void presentarSalida (String mensaje) {
        if (isVisible() != true) {
            setVisible(true);
        }
        jTextArea.append(mensaje);
        jTextArea.append("\n");
    }
    
    void restaurarEleccion(){
        eleccion = 0;
        this.jButtonGreedy.setEnabled(true);
        this.jProgressBarEstado.setValue(0);
        this.jButtonReload.setEnabled(true);
    }
    
    
    int getEleccion(){
        return eleccion;
    }
    
    
    void setValue( int estado){
        jProgressBarEstado.setValue(jProgressBarEstado.getValue()+estado);
    }
    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        jButtonGreedy = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jProgressBarEstado = new javax.swing.JProgressBar();
        jButtonReload = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Metaheurísticas: Práctica 2");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(730, 355));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(34, 43, 53));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(0, 51, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(730, 330));

        jTextArea.setEditable(false);
        jTextArea.setBackground(new java.awt.Color(153, 153, 153));
        jTextArea.setColumns(20);
        jTextArea.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jTextArea.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea.setRows(5);
        jTextArea.setAutoscrolls(false);
        jTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTextArea);

        jButtonGreedy.setBackground(new java.awt.Color(153, 153, 153));
        jButtonGreedy.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jButtonGreedy.setText("Colonia de hormigas");
        jButtonGreedy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonGreedy.setBorderPainted(false);
        jButtonGreedy.setFocusPainted(false);
        jButtonGreedy.setFocusable(false);
        jButtonGreedy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGreedyActionPerformed(evt);
            }
        });

        jButtonExit.setBackground(new java.awt.Color(248, 146, 41));
        jButtonExit.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jButtonExit.setText("Salir");
        jButtonExit.setBorderPainted(false);
        jButtonExit.setFocusPainted(false);
        jButtonExit.setFocusable(false);
        jButtonExit.setPreferredSize(new java.awt.Dimension(53, 18));
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccione una heurística");
        jLabel1.setFocusable(false);

        jProgressBarEstado.setBackground(new java.awt.Color(34, 43, 53));
        jProgressBarEstado.setForeground(new java.awt.Color(255, 255, 255));
        jProgressBarEstado.setMaximum(1000);
        jProgressBarEstado.setBorderPainted(false);
        jProgressBarEstado.setFocusable(false);

        jButtonReload.setBackground(new java.awt.Color(153, 153, 153));
        jButtonReload.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jButtonReload.setText("Recargar config");
        jButtonReload.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButtonReload.setBorderPainted(false);
        jButtonReload.setFocusPainted(false);
        jButtonReload.setFocusable(false);
        jButtonReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(jButtonGreedy, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                        .addComponent(jButtonReload, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jProgressBarEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jButtonGreedy, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonReload, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGreedyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGreedyActionPerformed
        eleccion = 1;
        jTextArea.removeAll();
        jTextArea.setText("");
        this.jButtonGreedy.setEnabled(false);
        this.jProgressBarEstado.setVisible(true);
        this.jButtonReload.setEnabled(false);
    }//GEN-LAST:event_jButtonGreedyActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        Main.exec.shutdownNow();
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReloadActionPerformed
        // TODO add your handling code here:
        
         eleccion = 2;
         jTextArea.removeAll();
         jTextArea.setText("Archivo de configuración recargado\n");
         this.jButtonGreedy.setEnabled(false);
         this.jButtonReload.setEnabled(false);
    }//GEN-LAST:event_jButtonReloadActionPerformed

    
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonGreedy;
    private javax.swing.JButton jButtonReload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBarEstado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea;
    // End of variables declaration//GEN-END:variables
}
